### ISSUE TITLE
could not parse 'oidc_discovery_ca_pem' value successfully

### ISSUE THREAD

**Issue by Leletir** [hashicorp/vault-plugin-auth-jwt#32] opened 2019-03-19 15:44 UTC
Hello,

I'm using vault 1.1.0-beta2 and I can't configure OIDC auth method, I have to say that I'm using my company certificate.

The command line I'm trying is:
```bash
vault auth enable oidc
vault write auth/oidc/config \
    oidc_discovery_url="url-of-my-provider" \
    oidc_client_id="<client-id>", \
    oidc_client_secret="<client-token>", \
    oidc_discovery_ca_pem=''content of `cat my.pem` "
```

As a result I have: 
```bash
Error writing data to auth/oidc/config: Error making API request.

URL: PUT <url-of-my-provider>/v1/auth/oidc/config
Code: 400. Errors:

* error checking discovery URL: could not parse 'oidc_discovery_ca_pem' value successfully
```

I also try via the gui, but I only I have option to fill the oidc_discovery_url and the certificate.
It seems to work (I got the pop up saying it's the auth method is activated) but when I try to use the OIDC authentification, is asking me for my token.

Did I miss something ?

Thank you.

**Comment by kalafut** [comment] 2019-03-26 16:13
Duplicate of: https://github.com/hashicorp/vault/issues/6442

Leaving this one open as there is some different info between the tickets.

**Comment by Leletir** [comment] 2019-03-27 14:03
Okay, thank you

**Closed** 2019-04-01 22:13 UTC
