### ISSUE TITLE
Vault OIDC cannot fetch g suite groups

### ISSUE THREAD

**Issue by frank1210** [hashicorp/vault-plugin-auth-jwt#179] opened 2021-08-13 18:59 UTC
When trying to login I get a 401 error at group fetching. I have tried different online solutions but nothing seems to help.

**Current vault config:**
> vault write auth/oidc/config -<<EOF
> {
>     "oidc_discovery_url": "https://accounts.google.com",
>     "oidc_client_id": "CLIENTID1",
>     "oidc_client_secret": "SECRET",
>     "default_role": "gmail",
>     "provider_config": {
>         "provider": "gsuite",
>         "gsuite_service_account": "/home/vault/sa2.json",
>         "gsuite_admin_impersonate": "Superadmin@domain.com",
>         "fetch_user_info": true,
>         "fetch_groups": true,
>         "groups_recurse_max_depth": 5
>     }
> }
> EOF

**Current vault role:**
> vault write auth/oidc/role/gmail \
> allowed_redirect_uris="https://vault.DOMAIN.com/ui/vault/auth/oidc/oidc/callback,http://localhost:8250/oidc/callback" \
> bound_audiences="CLIENTID1" \
> user_claim="sub" \
> policies="default" \
> groups_claim="groups"

**Error received:**

`failed to fetch groups: Get "https://www.googleapis.com/admin/directory/v1/groups?alt=json&fields=nextPageToken%2Cgroups%28email%29&prettyPrint=false&userKey=REDACTED": oauth2: cannot fetch token: 401 Unauthorized Response: { "error": "unauthorized_client", "error_description": "Client is unauthorized to retrieve access tokens using this method, or client not authorized for any of the scopes requested." }`

Domain-wide delegation is active on the service account and on google's admin console(using the numeric clientID from the service account). The following scopes are granted:

- https://www.googleapis.com/auth/admin.directory.user
- https://www.googleapis.com/auth/admin.directory.group

**Expected behavior**
be able to login and fetch user groups

**Environment:**
Vault Server Version (retrieve with vault status): 1.6.2
Vault CLI Version (retrieve with vault version): v1.6.2

**Comment by redbaron** [comment] 2022-10-18 12:02
Can't make it work in Vault v1.11.3 with very same symptoms :(

**Comment by austingebauer** [comment] 2022-10-18 15:41
Thanks, @redbaron. I was able to successfully set up the Vault OIDC and Google Workspace integration just now. I suspect this is a configuration issue and not a bug. Let me know if you are still having trouble @frank1210 and @mrnonz. Happy to help.

**Comment by smarkatov** [comment] 2023-01-03 16:51
Hi. 
I managed to fetch google groups with these scopes in domain-wide validation: 
```
https://www.googleapis.com/auth/admin.directory.group.readonly
https://www.googleapis.com/auth/admin.directory.user.readonly
https://www.googleapis.com/auth/admin.directory.group.member.readonly
https://www.googleapis.com/auth/admin.directory.domain.readonly
```
The following Vault configuration was supposed:
```
vault write auth/$AUTH0_PATH/config -<<EOF
{
    "oidc_discovery_url": "$AUTH0_DISCOVERY_URL",
    "oidc_client_id": "$AUTH0_CLIENT_ID",
    "oidc_client_secret": "$AUTH0_CLIENT_SECRET",
    "default_role": "$AUTH0_CLIENT_ROLE",
    "provider_config": {
        "provider": "gsuite",
        "domain": "global",
        "gsuite_service_account": "/vault/sa.json",
        "gsuite_admin_impersonate": "admin_email@mydomain.io",
        "fetch_groups": true,
        "groups_recurse_max_depth": 5
    }
}
EOF```

and created an identity role correspondingly:

```
vault write auth/$AUTH0_PATH/role/test_role -<<EOF
{
	"bound_audiences": "$AUTH0_CLIENT_ID",
	"allowed_redirect_uris": ["https://$VAULT_HOSTNAME/ui/vault/auth/$AUTH0_PATH/oidc/callback","http://localhost:8250/oidc/callback"],
	"user_claim": "email",
	"groups_claim": "groups", 
	"token_ttl": "1h",
	"token_policies":"reader",
	"oidc_scopes": "profile,email",
	"claim_mappings": {
		"email": "email"
	}
}    
EOF
```
Then, I've created an external group like this:
```
vault write identity/group name="dev-devops@mydomain.io" policies=dev-devops-policy type=external metadata=responsibility="DevOps Group"
GROUP_ID=$(vault read -field=id "identity/group/name/dev-devops@mydomain.io")

OIDC_GOOGLE_ACCESSOR=$(vault auth list -detailed -format json | jq -r '.["oidc-google/"].accessor')
vault write identity/group-alias name="dev-devops@mydomain.io" canonical_id=${GROUP_ID} mount_accessor=${OIDC_GOOGLE_ACCESSOR}
```

**Comment by austingebauer** [comment] 2023-02-16 21:45
I'm going to close this issue. I recently tested this workflow with success. I suspect this is a configuration issue given that others were able to get this working as well.

**Closed by austingebauer** 2023-02-16 21:45 UTC
